[project]
name = "uv-tools-migration"
version = "2025.06.08"
description = "Migrate any projects from pipenv to uv without pain"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "tomli-w==1.2.0",
]
